name: Go Format
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Run gofmt
        run: |
          files=$(gofmt -l .)
          if [[ -n "$files" ]]; then
            echo "The following files are not formatted correctly:"
            echo "$files"
            exit 1
          fi
        working-directory: backend
